FeastFreedom03/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FeastFreedom03.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        
    }
}

FeastFreedom03/Controllers/KitchenController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FeastFreedom03.Models;


namespace FeastFreedom03.Controllers
{
    public class KitchenController : Controller
    {
        private FeastFreedomEntities db = new FeastFreedomEntities();

        // GET: Kitchen
        public ActionResult Index()
        {
            ViewBag.Message = "WAAAAAAUUW! LOOK AT ALL THAT";
            @TempData["KitchenID"] = null; //Once the user returns to this page, clear the TempData
            return View(db.Kitchens.ToList());
            
        }




        // GET: Kitchen/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kitchen kitchen = db.Kitchens.Find(id);
            if (kitchen == null)
            {
                return HttpNotFound();
            }
            return View(kitchen);
        }




        // GET: Kitchen/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Kitchen/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KitchenID,KitchenName,KitchenEmail,KitchenPassword")] Kitchen kitchen) //Still unsure what exactly this does
        {
            if (ModelState.IsValid)
            {
                db.Kitchens.Add(kitchen); //If the form looks good, add the basic user info to database.
                db.SaveChanges();
                TempData["KitchenID"] = kitchen.KitchenID;  //Store auto-generated KitchenID in TempData. This will be passed to other methods.
                return RedirectToAction("EditHours");
            }
            return View(kitchen);
        }




        // GET: Kitchen/Edit/5
        public ActionResult Edit(int? id) //You can't edit a Kitchen's info unless you know it's corresponding KitchenID number
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kitchen kitchen = db.Kitchens.Find(id);
            if (kitchen == null)
            {
                return HttpNotFound();
            }
            return View(kitchen);
        }

        // POST: Kitchen/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KitchenID,KitchenName,KitchenEmail,KitchenPassword")] Kitchen kitchen) //What does this do?
        {
            if (ModelState.IsValid)
            {
                db.Entry(kitchen).State = EntityState.Modified; //If there is a change, Save it. If there isn't a change, there's nothing new to save.
                db.SaveChanges();
                return RedirectToAction("Kitchens");
            }
            
            return View(kitchen);
        }




        // GET: Kitchen/Delete/5
        public ActionResult Delete(int? id) //You need to know a Kitchen's KitchenID if you want to delete it.
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kitchen kitchen = db.Kitchens.Find(id);
            if (kitchen == null)
            {
                return HttpNotFound();
            }
            return View(kitchen);
        }
        [HttpGet]
        public ActionResult EditHours()
        {
            TempData.Keep(); //We are holding the auto-generated KitchenID in TempData. 
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditHours(KitchenHOOp kitchenHours)
        {
            TempData.Keep();
            if (ModelState.IsValid)
            {
                kitchenHours.KitchenID = (int) @TempData["KitchenID"]; //Assign the carried-over KitchenID to THIS PARTICULAR INSTANCE of a KitchenHOOp Object/Row.
                db.KitchenHOOps.Add(kitchenHours);      //We have to know to which KitchenID we are assigning these hours. If we don't know the ID, we don't know which Kitchen we're talking about.
                db.SaveChanges();
                return RedirectToAction("EditMenu", TempData["KitchenID"]);
            }
            return RedirectToAction("EditMenu", TempData["KitchenID"]);
        }

        public ActionResult ListHours() //List all the data in our KitchenHOOp (Hours of Operation) database.
        {
            List<KitchenHOOp> hoursOfOperation = db.KitchenHOOps.ToList();
            return View(hoursOfOperation);
        }

        //henlo

        [HttpGet]
        public ActionResult EditMenu() //Let a Kitchen add food items to its menu. For the sake of simplicity, each Kitchen has one menu.
        {
            TempData.Keep();        //Hold on to TempData["KitchenID"] for now.
            return View();
        }

        [HttpPost]
        public ActionResult EditMenu(Item item)
        {
            if (ModelState.IsValid)
            {
                TempData.Keep();
                item.KitchenID = (int)@TempData["KitchenID"]; //Assign the KitchenID held in TempData to THIS PARTICULAR INSTANCE of an Item Object/Row.
                db.Items.Add(item);                 //If you don't know the item's KitchenID, you don't know which Kitchen sells it! The KitchenID is a foreign key.
                db.SaveChanges();                   //For now, TempData will be set to null once the user navigates back to the Kitchen/Index view. See above Index Action Method.
                
            }
            return RedirectToAction("EditMenu", TempData["KitchenID"]);
        }




        // POST: Kitchen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kitchen kitchen = db.Kitchens.Find(id);
            db.Kitchens.Remove(kitchen);
            db.SaveChanges();
            return RedirectToAction("Index");
        }




        public ActionResult Items() //This list every item sold by every restaurant. Given more time, we could implement more sophisticated data structures.
        {
            List<Item> menuItems = db.Items.ToList();
            return View(menuItems);
        }





        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FeastFreedom03/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FeastFreedom03/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FeastFreedom03/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    @*<h1>Feast Freedom</h1>
        <p class="lead">Welcome To <i>Feast Freedom!</i></p>*@
    <div align="center">
        <a href="@Url.Action("Index", "Kitchen")">
            <img src="https://66.media.tumblr.com/4d14a83ff2c7c949a1aaa57c3f660b8d/tumblr_p6b6weQnJG1vbdodoo1_500.gifv" height="250" align="middle" />
        </a>
        <br />
        <br />
        <p>
            <img src="https://static.wixstatic.com/media/3aee97_bba1dbc86f7445229fc322cec7de5a95~mv2.gif" height="70" />
            <a href="@Url.Action("Index", "Kitchen")" id="order-btn" class="btn btn-primary btn-lg" align="center">Place Your Order &raquo;</a>
            <img src="https://thumbs.gfycat.com/FixedPolishedEuropeanfiresalamander-size_restricted.gif" height="50" />
        </p>
        @*@Html.ActionLink("This is a test", "About", new { @class = "btn"})*@
    </div>

</div>

<div class="row">
    <div class="col-md-4">
        <h2>
            <img src="https://data.whicdn.com/images/204707563/original.gif" height="30" />
            Feeling Hungry?
        </h2>
        <p>
            Find all of your favorite restaurants in one place!
        </p>
        <p><a class="btn btn-default" href="@Url.Action("Index", "Kitchen")">View Kitchens &raquo;</a></p>
    </div>
    @*<div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>*@
    @*<div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>*@
</div>